// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: armies.sql

package database

import (
	"context"
)

const batchCreateArmies = `-- name: BatchCreateArmies :exec
INSERT INTO armies (
    army_id,
    owner,
    coords,
    troops,
    dest_x,
    dest_y,
    upkeep_city_id
)
SELECT
    v.army_id,
    v.owner,
    ROW(v.x, v.y)::coordinates,
    v.troops::jsonb,
    NULLIF(v.dest_x, -1),
    NULLIF(v.dest_y, -1),
    NULLIF(v.upkeep_city_id, '')
FROM (
    SELECT
        UNNEST($1::text[])        AS army_id,
        UNNEST($2::text[])          AS owner,
        UNNEST($3::int[])               AS x,
        UNNEST($4::int[])               AS y,
        UNNEST($5::text[])     AS troops,
        UNNEST($6::int[])          AS dest_x,
        UNNEST($7::int[])          AS dest_y,
        UNNEST($8::text[]) AS upkeep_city_id
) AS v
`

type BatchCreateArmiesParams struct {
	ArmyIds       []string `json:"army_ids"`
	Owners        []string `json:"owners"`
	Xs            []int32  `json:"xs"`
	Ys            []int32  `json:"ys"`
	TroopsList    []string `json:"troops_list"`
	DestXs        []int32  `json:"dest_xs"`
	DestYs        []int32  `json:"dest_ys"`
	UpkeepCityIds []string `json:"upkeep_city_ids"`
}

func (q *Queries) BatchCreateArmies(ctx context.Context, arg BatchCreateArmiesParams) error {
	_, err := q.db.Exec(ctx, batchCreateArmies,
		arg.ArmyIds,
		arg.Owners,
		arg.Xs,
		arg.Ys,
		arg.TroopsList,
		arg.DestXs,
		arg.DestYs,
		arg.UpkeepCityIds,
	)
	return err
}

const batchUpdateArmies = `-- name: BatchUpdateArmies :exec
UPDATE armies AS a
SET
    owner          = v.owner,
    coords         = ROW(v.x, v.y)::coordinates,
    troops         = v.troops::jsonb,
    dest_x         = NULLIF(v.dest_x, -1),
    dest_y         = NULLIF(v.dest_y, -1),
    upkeep_city_id = NULLIF(v.upkeep_city_id, '')
FROM (
    SELECT
        UNNEST($1::text[])        AS army_id,
        UNNEST($2::text[])          AS owner,
        UNNEST($3::int[])               AS x,
        UNNEST($4::int[])               AS y,
        UNNEST($5::text[])     AS troops,
        UNNEST($6::int[])          AS dest_x,
        UNNEST($7::int[])          AS dest_y,
        UNNEST($8::text[]) AS upkeep_city_id
) AS v
WHERE a.army_id = v.army_id
`

type BatchUpdateArmiesParams struct {
	ArmyIds       []string `json:"army_ids"`
	Owners        []string `json:"owners"`
	Xs            []int32  `json:"xs"`
	Ys            []int32  `json:"ys"`
	TroopsList    []string `json:"troops_list"`
	DestXs        []int32  `json:"dest_xs"`
	DestYs        []int32  `json:"dest_ys"`
	UpkeepCityIds []string `json:"upkeep_city_ids"`
}

func (q *Queries) BatchUpdateArmies(ctx context.Context, arg BatchUpdateArmiesParams) error {
	_, err := q.db.Exec(ctx, batchUpdateArmies,
		arg.ArmyIds,
		arg.Owners,
		arg.Xs,
		arg.Ys,
		arg.TroopsList,
		arg.DestXs,
		arg.DestYs,
		arg.UpkeepCityIds,
	)
	return err
}

const createArmy = `-- name: CreateArmy :exec
INSERT INTO armies (
    army_id,
    owner,
    coords,
    troops,
    dest_x,
    dest_y,
    upkeep_city_id
)
VALUES (
    $1,
    $2,
    ROW($3::int4, $4::int4)::coordinates,
    $5,
    $6,
    $7,
    $8
)
`

type CreateArmyParams struct {
	ArmyID       string  `json:"army_id"`
	Owner        string  `json:"owner"`
	X            int32   `json:"x"`
	Y            int32   `json:"y"`
	Troops       []byte  `json:"troops"`
	DestX        *int32  `json:"dest_x"`
	DestY        *int32  `json:"dest_y"`
	UpkeepCityID *string `json:"upkeep_city_id"`
}

func (q *Queries) CreateArmy(ctx context.Context, arg CreateArmyParams) error {
	_, err := q.db.Exec(ctx, createArmy,
		arg.ArmyID,
		arg.Owner,
		arg.X,
		arg.Y,
		arg.Troops,
		arg.DestX,
		arg.DestY,
		arg.UpkeepCityID,
	)
	return err
}

const deleteArmy = `-- name: DeleteArmy :exec
DELETE FROM armies
WHERE army_id = $1
`

func (q *Queries) DeleteArmy(ctx context.Context, armyID string) error {
	_, err := q.db.Exec(ctx, deleteArmy, armyID)
	return err
}

const getAllArmies = `-- name: GetAllArmies :many
SELECT
    army_id,
    owner,
    (coords).x::int4 AS x,
    (coords).y::int4 AS y,
    troops,
    dest_x,
    dest_y,
    upkeep_city_id
FROM armies
`

type GetAllArmiesRow struct {
	ArmyID       string  `json:"army_id"`
	Owner        string  `json:"owner"`
	X            int32   `json:"x"`
	Y            int32   `json:"y"`
	Troops       []byte  `json:"troops"`
	DestX        *int32  `json:"dest_x"`
	DestY        *int32  `json:"dest_y"`
	UpkeepCityID *string `json:"upkeep_city_id"`
}

func (q *Queries) GetAllArmies(ctx context.Context) ([]GetAllArmiesRow, error) {
	rows, err := q.db.Query(ctx, getAllArmies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllArmiesRow
	for rows.Next() {
		var i GetAllArmiesRow
		if err := rows.Scan(
			&i.ArmyID,
			&i.Owner,
			&i.X,
			&i.Y,
			&i.Troops,
			&i.DestX,
			&i.DestY,
			&i.UpkeepCityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
