// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: buildings.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBuilding = `-- name: CreateBuilding :exec
INSERT INTO buildings (
    building_id,
    city_id,
    type,
    level,
    target_level,
    coords,
    construction_start,
    construction_end
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    ROW($6::int4, $7::int4)::coordinates,
    $8,
    $9
)
`

type CreateBuildingParams struct {
	BuildingID        string           `json:"building_id"`
	CityID            string           `json:"city_id"`
	Type              string           `json:"type"`
	Level             int32            `json:"level"`
	TargetLevel       int32            `json:"target_level"`
	X                 int32            `json:"x"`
	Y                 int32            `json:"y"`
	ConstructionStart pgtype.Timestamp `json:"construction_start"`
	ConstructionEnd   pgtype.Timestamp `json:"construction_end"`
}

func (q *Queries) CreateBuilding(ctx context.Context, arg CreateBuildingParams) error {
	_, err := q.db.Exec(ctx, createBuilding,
		arg.BuildingID,
		arg.CityID,
		arg.Type,
		arg.Level,
		arg.TargetLevel,
		arg.X,
		arg.Y,
		arg.ConstructionStart,
		arg.ConstructionEnd,
	)
	return err
}
