// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cities.sql

package database

import (
	"context"
)

const batchUpdateCities = `-- name: BatchUpdateCities :exec
UPDATE cities AS c
SET
    type            = v.type,
    owner           = NULLIF(v.owner, ''),
    name            = v.name,
    population      = v.population,
    population_cap  = v.population_cap,
    start_coord     = POINT(v.start_x, v.start_y),
    size            = v.size,
    updated_at      = NOW()
FROM (
    SELECT
        UNNEST($1::text[])         AS city_id,
        UNNEST($2::text[])            AS type,
        UNNEST($3::text[])           AS owner,
        UNNEST($4::text[])            AS name,
        UNNEST($5::float8[])    AS population,
        UNNEST($6::float8[]) AS population_cap,
        UNNEST($7::int[])          AS start_x,
        UNNEST($8::int[])          AS start_y,
        UNNEST($9::int[])             AS size
) AS v
WHERE c.city_id = v.city_id
`

type BatchUpdateCitiesParams struct {
	CityIds        []string  `json:"city_ids"`
	Types          []string  `json:"types"`
	Owners         []string  `json:"owners"`
	Names          []string  `json:"names"`
	Populations    []float64 `json:"populations"`
	PopulationCaps []float64 `json:"population_caps"`
	StartXs        []int32   `json:"start_xs"`
	StartYs        []int32   `json:"start_ys"`
	Sizes          []int32   `json:"sizes"`
}

func (q *Queries) BatchUpdateCities(ctx context.Context, arg BatchUpdateCitiesParams) error {
	_, err := q.db.Exec(ctx, batchUpdateCities,
		arg.CityIds,
		arg.Types,
		arg.Owners,
		arg.Names,
		arg.Populations,
		arg.PopulationCaps,
		arg.StartXs,
		arg.StartYs,
		arg.Sizes,
	)
	return err
}

const createCity = `-- name: CreateCity :exec
INSERT INTO cities (
    city_id, type, owner, name, population, population_cap,
    start_coord, size
)
VALUES (
    $1, $2, $3, $4, $5, $6, COORDINATES($7, $8), $9
)
`

type CreateCityParams struct {
	CityID        string      `json:"city_id"`
	Type          string      `json:"type"`
	Owner         *string     `json:"owner"`
	Name          string      `json:"name"`
	Population    float64     `json:"population"`
	PopulationCap float64     `json:"population_cap"`
	Coordinates   interface{} `json:"coordinates"`
	Coordinates_2 interface{} `json:"coordinates_2"`
	Size          int32       `json:"size"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) error {
	_, err := q.db.Exec(ctx, createCity,
		arg.CityID,
		arg.Type,
		arg.Owner,
		arg.Name,
		arg.Population,
		arg.PopulationCap,
		arg.Coordinates,
		arg.Coordinates_2,
		arg.Size,
	)
	return err
}

const deleteCity = `-- name: DeleteCity :exec
DELETE FROM cities
WHERE city_id = $1
`

func (q *Queries) DeleteCity(ctx context.Context, cityID string) error {
	_, err := q.db.Exec(ctx, deleteCity, cityID)
	return err
}

const getAllCities = `-- name: GetAllCities :many
SELECT city_id, type, owner, name, population, population_cap, start_coords, size, created_at, updated_at FROM cities
`

func (q *Queries) GetAllCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.Query(ctx, getAllCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []City
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.CityID,
			&i.Type,
			&i.Owner,
			&i.Name,
			&i.Population,
			&i.PopulationCap,
			&i.StartCoords,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCity = `-- name: UpdateCity :exec
UPDATE cities
SET
    type            = $2,
    owner           = $3,
    name            = $4,
    population      = $5,
    population_cap  = $6,
    start_coord     = COORDINATES($7, $8),
    size            = $9,
    updated_at      = NOW()
WHERE city_id = $1
`

type UpdateCityParams struct {
	CityID        string      `json:"city_id"`
	Type          string      `json:"type"`
	Owner         *string     `json:"owner"`
	Name          string      `json:"name"`
	Population    float64     `json:"population"`
	PopulationCap float64     `json:"population_cap"`
	Coordinates   interface{} `json:"coordinates"`
	Coordinates_2 interface{} `json:"coordinates_2"`
	Size          int32       `json:"size"`
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) error {
	_, err := q.db.Exec(ctx, updateCity,
		arg.CityID,
		arg.Type,
		arg.Owner,
		arg.Name,
		arg.Population,
		arg.PopulationCap,
		arg.Coordinates,
		arg.Coordinates_2,
		arg.Size,
	)
	return err
}
