// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cities.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCreateCities = `-- name: BatchCreateCities :exec
INSERT INTO cities (
    city_id,
    type,
    owner,
    name,
    population,
    population_cap,
    population_basis,
    militia_population,
    militia_target,
    tax_rate_percent,
    start_coords,
    size
)
SELECT
    v.city_id,
    v.type,
    NULLIF(v.owner, ''),
    v.name,
    v.population,
    v.population_cap,
    v.population_basis,
    v.militia_population,
    v.militia_target,
    v.tax_rate_percent,
    ROW(v.start_x, v.start_y)::coordinates,
    v.size
FROM (
    SELECT
        UNNEST($1::text[])           AS city_id,
        UNNEST($2::text[])              AS type,
        UNNEST($3::text[])             AS owner,
        UNNEST($4::text[])              AS name,
        UNNEST($5::float8[])      AS population,
        UNNEST($6::float8[])  AS population_cap,
        UNNEST($7::float8[]) AS population_basis,
        UNNEST($8::float8[]) AS militia_population,
        UNNEST($9::float8[]) AS militia_target,
        UNNEST($10::int[])  AS tax_rate_percent,
        UNNEST($11::int[])            AS start_x,
        UNNEST($12::int[])            AS start_y,
        UNNEST($13::int[])               AS size
) AS v
`

type BatchCreateCitiesParams struct {
	CityIds            []string  `json:"city_ids"`
	Types              []string  `json:"types"`
	Owners             []string  `json:"owners"`
	Names              []string  `json:"names"`
	Populations        []float64 `json:"populations"`
	PopulationCaps     []float64 `json:"population_caps"`
	PopulationBases    []float64 `json:"population_bases"`
	MilitiaPopulations []float64 `json:"militia_populations"`
	MilitiaTargets     []float64 `json:"militia_targets"`
	TaxRatePercents    []int32   `json:"tax_rate_percents"`
	StartXs            []int32   `json:"start_xs"`
	StartYs            []int32   `json:"start_ys"`
	Sizes              []int32   `json:"sizes"`
}

func (q *Queries) BatchCreateCities(ctx context.Context, arg BatchCreateCitiesParams) error {
	_, err := q.db.Exec(ctx, batchCreateCities,
		arg.CityIds,
		arg.Types,
		arg.Owners,
		arg.Names,
		arg.Populations,
		arg.PopulationCaps,
		arg.PopulationBases,
		arg.MilitiaPopulations,
		arg.MilitiaTargets,
		arg.TaxRatePercents,
		arg.StartXs,
		arg.StartYs,
		arg.Sizes,
	)
	return err
}

const batchUpdateCities = `-- name: BatchUpdateCities :exec
UPDATE cities AS c
SET
    type            = v.type,
    owner           = NULLIF(v.owner, ''),
    name            = v.name,
    population      = v.population,
    population_cap  = v.population_cap,
    population_basis = v.population_basis,
    militia_population = v.militia_population,
    militia_target = v.militia_target,
    tax_rate_percent = v.tax_rate_percent,
    start_coords    = ROW(v.start_x, v.start_y)::coordinates,
    size            = v.size
FROM (
    SELECT
        UNNEST($1::text[])          AS city_id,
        UNNEST($2::text[])             AS type,
        UNNEST($3::text[])            AS owner,
        UNNEST($4::text[])             AS name,
        UNNEST($5::float8[])     AS population,
        UNNEST($6::float8[]) AS population_cap,
        UNNEST($7::float8[]) AS population_basis,
        UNNEST($8::float8[]) AS militia_population,
        UNNEST($9::float8[]) AS militia_target,
        UNNEST($10::int[])  AS tax_rate_percent,
        UNNEST($11::int[])           AS start_x,
        UNNEST($12::int[])           AS start_y,
        UNNEST($13::int[])              AS size
) AS v
WHERE c.city_id = v.city_id
`

type BatchUpdateCitiesParams struct {
	CityIds            []string  `json:"city_ids"`
	Types              []string  `json:"types"`
	Owners             []string  `json:"owners"`
	Names              []string  `json:"names"`
	Populations        []float64 `json:"populations"`
	PopulationCaps     []float64 `json:"population_caps"`
	PopulationBases    []float64 `json:"population_bases"`
	MilitiaPopulations []float64 `json:"militia_populations"`
	MilitiaTargets     []float64 `json:"militia_targets"`
	TaxRatePercents    []int32   `json:"tax_rate_percents"`
	StartXs            []int32   `json:"start_xs"`
	StartYs            []int32   `json:"start_ys"`
	Sizes              []int32   `json:"sizes"`
}

func (q *Queries) BatchUpdateCities(ctx context.Context, arg BatchUpdateCitiesParams) error {
	_, err := q.db.Exec(ctx, batchUpdateCities,
		arg.CityIds,
		arg.Types,
		arg.Owners,
		arg.Names,
		arg.Populations,
		arg.PopulationCaps,
		arg.PopulationBases,
		arg.MilitiaPopulations,
		arg.MilitiaTargets,
		arg.TaxRatePercents,
		arg.StartXs,
		arg.StartYs,
		arg.Sizes,
	)
	return err
}

const createCity = `-- name: CreateCity :exec
INSERT INTO cities (
    city_id,
    type,
    owner,
    name,
    population,
    population_cap,
    population_basis,
    militia_population,
    militia_target,
    tax_rate_percent,
    start_coords,
    size
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    ROW($11::int4, $12::int4)::coordinates,
    $13
)
`

type CreateCityParams struct {
	CityID            string  `json:"city_id"`
	Type              string  `json:"type"`
	Owner             *string `json:"owner"`
	Name              string  `json:"name"`
	Population        float64 `json:"population"`
	PopulationCap     float64 `json:"population_cap"`
	PopulationBasis   float64 `json:"population_basis"`
	MilitiaPopulation float64 `json:"militia_population"`
	MilitiaTarget     float64 `json:"militia_target"`
	TaxRatePercent    int32   `json:"tax_rate_percent"`
	StartX            int32   `json:"start_x"`
	StartY            int32   `json:"start_y"`
	Size              int32   `json:"size"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) error {
	_, err := q.db.Exec(ctx, createCity,
		arg.CityID,
		arg.Type,
		arg.Owner,
		arg.Name,
		arg.Population,
		arg.PopulationCap,
		arg.PopulationBasis,
		arg.MilitiaPopulation,
		arg.MilitiaTarget,
		arg.TaxRatePercent,
		arg.StartX,
		arg.StartY,
		arg.Size,
	)
	return err
}

const deleteCity = `-- name: DeleteCity :exec
DELETE FROM cities
WHERE city_id = $1
`

func (q *Queries) DeleteCity(ctx context.Context, cityID string) error {
	_, err := q.db.Exec(ctx, deleteCity, cityID)
	return err
}

const getAllCities = `-- name: GetAllCities :many
SELECT
    city_id,
    type,
    owner,
    name,
    population,
    population_cap,
    population_basis,
    militia_population,
    militia_target,
    tax_rate_percent,
    (start_coords).x::int4 AS start_x,
    (start_coords).y::int4 AS start_y,
    size,
    created_at,
    updated_at
FROM cities
`

type GetAllCitiesRow struct {
	CityID            string           `json:"city_id"`
	Type              string           `json:"type"`
	Owner             *string          `json:"owner"`
	Name              string           `json:"name"`
	Population        float64          `json:"population"`
	PopulationCap     float64          `json:"population_cap"`
	PopulationBasis   float64          `json:"population_basis"`
	MilitiaPopulation float64          `json:"militia_population"`
	MilitiaTarget     float64          `json:"militia_target"`
	TaxRatePercent    int32            `json:"tax_rate_percent"`
	StartX            int32            `json:"start_x"`
	StartY            int32            `json:"start_y"`
	Size              int32            `json:"size"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAllCities(ctx context.Context) ([]GetAllCitiesRow, error) {
	rows, err := q.db.Query(ctx, getAllCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCitiesRow
	for rows.Next() {
		var i GetAllCitiesRow
		if err := rows.Scan(
			&i.CityID,
			&i.Type,
			&i.Owner,
			&i.Name,
			&i.Population,
			&i.PopulationCap,
			&i.PopulationBasis,
			&i.MilitiaPopulation,
			&i.MilitiaTarget,
			&i.TaxRatePercent,
			&i.StartX,
			&i.StartY,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCitiesByOwner = `-- name: GetCitiesByOwner :many
SELECT
    city_id,
    type,
    owner,
    name,
    population,
    population_cap,
    population_basis,
    militia_population,
    militia_target,
    tax_rate_percent,
    (start_coords).x::int4 AS start_x,
    (start_coords).y::int4 AS start_y,
    size,
    created_at,
    updated_at
FROM cities
WHERE owner = $1
`

type GetCitiesByOwnerRow struct {
	CityID            string           `json:"city_id"`
	Type              string           `json:"type"`
	Owner             *string          `json:"owner"`
	Name              string           `json:"name"`
	Population        float64          `json:"population"`
	PopulationCap     float64          `json:"population_cap"`
	PopulationBasis   float64          `json:"population_basis"`
	MilitiaPopulation float64          `json:"militia_population"`
	MilitiaTarget     float64          `json:"militia_target"`
	TaxRatePercent    int32            `json:"tax_rate_percent"`
	StartX            int32            `json:"start_x"`
	StartY            int32            `json:"start_y"`
	Size              int32            `json:"size"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetCitiesByOwner(ctx context.Context, owner *string) ([]GetCitiesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getCitiesByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCitiesByOwnerRow
	for rows.Next() {
		var i GetCitiesByOwnerRow
		if err := rows.Scan(
			&i.CityID,
			&i.Type,
			&i.Owner,
			&i.Name,
			&i.Population,
			&i.PopulationCap,
			&i.PopulationBasis,
			&i.MilitiaPopulation,
			&i.MilitiaTarget,
			&i.TaxRatePercent,
			&i.StartX,
			&i.StartY,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCity = `-- name: UpdateCity :exec
UPDATE cities
SET
    type            = $1,
    owner           = $2,
    name            = $3,
    population      = $4,
    population_cap  = $5,
    population_basis = $6,
    militia_population = $7,
    militia_target = $8,
    tax_rate_percent = $9,
    start_coords    = ROW($10::int4, $11::int4)::coordinates,
    size            = $12,
    updated_at      = NOW()
WHERE city_id = $13
`

type UpdateCityParams struct {
	Type              string  `json:"type"`
	Owner             *string `json:"owner"`
	Name              string  `json:"name"`
	Population        float64 `json:"population"`
	PopulationCap     float64 `json:"population_cap"`
	PopulationBasis   float64 `json:"population_basis"`
	MilitiaPopulation float64 `json:"militia_population"`
	MilitiaTarget     float64 `json:"militia_target"`
	TaxRatePercent    int32   `json:"tax_rate_percent"`
	StartX            int32   `json:"start_x"`
	StartY            int32   `json:"start_y"`
	Size              int32   `json:"size"`
	CityID            string  `json:"city_id"`
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) error {
	_, err := q.db.Exec(ctx, updateCity,
		arg.Type,
		arg.Owner,
		arg.Name,
		arg.Population,
		arg.PopulationCap,
		arg.PopulationBasis,
		arg.MilitiaPopulation,
		arg.MilitiaTarget,
		arg.TaxRatePercent,
		arg.StartX,
		arg.StartY,
		arg.Size,
		arg.CityID,
	)
	return err
}
