// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cities.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCreateCities = `-- name: BatchCreateCities :exec
INSERT INTO cities (
    city_id,
    type,
    owner,
    name,
    population,
    population_cap,
    garrison_population,
    garrison_percent,
    tax_rate_percent,
    start_coords,
    size
)
SELECT
    v.city_id,
    v.type,
    NULLIF(v.owner, ''),
    v.name,
    v.population,
    v.population_cap,
    v.garrison_population,
    v.garrison_percent,
    v.tax_rate_percent,
    ROW(v.start_x, v.start_y)::coordinates,
    v.size
FROM (
    SELECT
        UNNEST($1::text[])           AS city_id,
        UNNEST($2::text[])              AS type,
        UNNEST($3::text[])             AS owner,
        UNNEST($4::text[])              AS name,
        UNNEST($5::float8[])      AS population,
        UNNEST($6::float8[])  AS population_cap,
        UNNEST($7::float8[]) AS garrison_population,
        UNNEST($8::int[])   AS garrison_percent,
        UNNEST($9::int[])  AS tax_rate_percent,
        UNNEST($10::int[])            AS start_x,
        UNNEST($11::int[])            AS start_y,
        UNNEST($12::int[])               AS size
) AS v
`

type BatchCreateCitiesParams struct {
	CityIds             []string  `json:"city_ids"`
	Types               []string  `json:"types"`
	Owners              []string  `json:"owners"`
	Names               []string  `json:"names"`
	Populations         []float64 `json:"populations"`
	PopulationCaps      []float64 `json:"population_caps"`
	GarrisonPopulations []float64 `json:"garrison_populations"`
	GarrisonPercents    []int32   `json:"garrison_percents"`
	TaxRatePercents     []int32   `json:"tax_rate_percents"`
	StartXs             []int32   `json:"start_xs"`
	StartYs             []int32   `json:"start_ys"`
	Sizes               []int32   `json:"sizes"`
}

func (q *Queries) BatchCreateCities(ctx context.Context, arg BatchCreateCitiesParams) error {
	_, err := q.db.Exec(ctx, batchCreateCities,
		arg.CityIds,
		arg.Types,
		arg.Owners,
		arg.Names,
		arg.Populations,
		arg.PopulationCaps,
		arg.GarrisonPopulations,
		arg.GarrisonPercents,
		arg.TaxRatePercents,
		arg.StartXs,
		arg.StartYs,
		arg.Sizes,
	)
	return err
}

const batchUpdateCities = `-- name: BatchUpdateCities :exec
UPDATE cities AS c
SET
    type            = v.type,
    owner           = NULLIF(v.owner, ''),
    name            = v.name,
    population      = v.population,
    population_cap  = v.population_cap,
    garrison_population = v.garrison_population,
    garrison_percent = v.garrison_percent,
    tax_rate_percent = v.tax_rate_percent,
    start_coords    = ROW(v.start_x, v.start_y)::coordinates,
    size            = v.size
FROM (
    SELECT
        UNNEST($1::text[])          AS city_id,
        UNNEST($2::text[])             AS type,
        UNNEST($3::text[])            AS owner,
        UNNEST($4::text[])             AS name,
        UNNEST($5::float8[])     AS population,
        UNNEST($6::float8[]) AS population_cap,
        UNNEST($7::float8[]) AS garrison_population,
        UNNEST($8::int[])  AS garrison_percent,
        UNNEST($9::int[])  AS tax_rate_percent,
        UNNEST($10::int[])           AS start_x,
        UNNEST($11::int[])           AS start_y,
        UNNEST($12::int[])              AS size
) AS v
WHERE c.city_id = v.city_id
`

type BatchUpdateCitiesParams struct {
	CityIds             []string  `json:"city_ids"`
	Types               []string  `json:"types"`
	Owners              []string  `json:"owners"`
	Names               []string  `json:"names"`
	Populations         []float64 `json:"populations"`
	PopulationCaps      []float64 `json:"population_caps"`
	GarrisonPopulations []float64 `json:"garrison_populations"`
	GarrisonPercents    []int32   `json:"garrison_percents"`
	TaxRatePercents     []int32   `json:"tax_rate_percents"`
	StartXs             []int32   `json:"start_xs"`
	StartYs             []int32   `json:"start_ys"`
	Sizes               []int32   `json:"sizes"`
}

func (q *Queries) BatchUpdateCities(ctx context.Context, arg BatchUpdateCitiesParams) error {
	_, err := q.db.Exec(ctx, batchUpdateCities,
		arg.CityIds,
		arg.Types,
		arg.Owners,
		arg.Names,
		arg.Populations,
		arg.PopulationCaps,
		arg.GarrisonPopulations,
		arg.GarrisonPercents,
		arg.TaxRatePercents,
		arg.StartXs,
		arg.StartYs,
		arg.Sizes,
	)
	return err
}

const createCity = `-- name: CreateCity :exec
INSERT INTO cities (
    city_id,
    type,
    owner,
    name,
    population,
    population_cap,
    garrison_population,
    garrison_percent,
    tax_rate_percent,
    start_coords,
    size
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    ROW($10::int4, $11::int4)::coordinates,
    $12
)
`

type CreateCityParams struct {
	CityID             string  `json:"city_id"`
	Type               string  `json:"type"`
	Owner              *string `json:"owner"`
	Name               string  `json:"name"`
	Population         float64 `json:"population"`
	PopulationCap      float64 `json:"population_cap"`
	GarrisonPopulation float64 `json:"garrison_population"`
	GarrisonPercent    int32   `json:"garrison_percent"`
	TaxRatePercent     int32   `json:"tax_rate_percent"`
	StartX             int32   `json:"start_x"`
	StartY             int32   `json:"start_y"`
	Size               int32   `json:"size"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) error {
	_, err := q.db.Exec(ctx, createCity,
		arg.CityID,
		arg.Type,
		arg.Owner,
		arg.Name,
		arg.Population,
		arg.PopulationCap,
		arg.GarrisonPopulation,
		arg.GarrisonPercent,
		arg.TaxRatePercent,
		arg.StartX,
		arg.StartY,
		arg.Size,
	)
	return err
}

const deleteCity = `-- name: DeleteCity :exec
DELETE FROM cities
WHERE city_id = $1
`

func (q *Queries) DeleteCity(ctx context.Context, cityID string) error {
	_, err := q.db.Exec(ctx, deleteCity, cityID)
	return err
}

const getAllCities = `-- name: GetAllCities :many
SELECT
    city_id,
    type,
    owner,
    name,
    population,
    population_cap,
    garrison_population,
    garrison_percent,
    tax_rate_percent,
    (start_coords).x::int4 AS start_x,
    (start_coords).y::int4 AS start_y,
    size,
    created_at,
    updated_at
FROM cities
`

type GetAllCitiesRow struct {
	CityID             string           `json:"city_id"`
	Type               string           `json:"type"`
	Owner              *string          `json:"owner"`
	Name               string           `json:"name"`
	Population         float64          `json:"population"`
	PopulationCap      float64          `json:"population_cap"`
	GarrisonPopulation float64          `json:"garrison_population"`
	GarrisonPercent    int32            `json:"garrison_percent"`
	TaxRatePercent     int32            `json:"tax_rate_percent"`
	StartX             int32            `json:"start_x"`
	StartY             int32            `json:"start_y"`
	Size               int32            `json:"size"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAllCities(ctx context.Context) ([]GetAllCitiesRow, error) {
	rows, err := q.db.Query(ctx, getAllCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCitiesRow
	for rows.Next() {
		var i GetAllCitiesRow
		if err := rows.Scan(
			&i.CityID,
			&i.Type,
			&i.Owner,
			&i.Name,
			&i.Population,
			&i.PopulationCap,
			&i.GarrisonPopulation,
			&i.GarrisonPercent,
			&i.TaxRatePercent,
			&i.StartX,
			&i.StartY,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCitiesByOwner = `-- name: GetCitiesByOwner :many
SELECT
    city_id,
    type,
    owner,
    name,
    population,
    population_cap,
    garrison_population,
    garrison_percent,
    tax_rate_percent,
    (start_coords).x::int4 AS start_x,
    (start_coords).y::int4 AS start_y,
    size,
    created_at,
    updated_at
FROM cities
WHERE owner = $1
`

type GetCitiesByOwnerRow struct {
	CityID             string           `json:"city_id"`
	Type               string           `json:"type"`
	Owner              *string          `json:"owner"`
	Name               string           `json:"name"`
	Population         float64          `json:"population"`
	PopulationCap      float64          `json:"population_cap"`
	GarrisonPopulation float64          `json:"garrison_population"`
	GarrisonPercent    int32            `json:"garrison_percent"`
	TaxRatePercent     int32            `json:"tax_rate_percent"`
	StartX             int32            `json:"start_x"`
	StartY             int32            `json:"start_y"`
	Size               int32            `json:"size"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetCitiesByOwner(ctx context.Context, owner *string) ([]GetCitiesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getCitiesByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCitiesByOwnerRow
	for rows.Next() {
		var i GetCitiesByOwnerRow
		if err := rows.Scan(
			&i.CityID,
			&i.Type,
			&i.Owner,
			&i.Name,
			&i.Population,
			&i.PopulationCap,
			&i.GarrisonPopulation,
			&i.GarrisonPercent,
			&i.TaxRatePercent,
			&i.StartX,
			&i.StartY,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCity = `-- name: UpdateCity :exec
UPDATE cities
SET
    type            = $1,
    owner           = $2,
    name            = $3,
    population      = $4,
    population_cap  = $5,
    garrison_population = $6,
    garrison_percent = $7,
    tax_rate_percent = $8,
    start_coords    = ROW($9::int4, $10::int4)::coordinates,
    size            = $11,
    updated_at      = NOW()
WHERE city_id = $12
`

type UpdateCityParams struct {
	Type               string  `json:"type"`
	Owner              *string `json:"owner"`
	Name               string  `json:"name"`
	Population         float64 `json:"population"`
	PopulationCap      float64 `json:"population_cap"`
	GarrisonPopulation float64 `json:"garrison_population"`
	GarrisonPercent    int32   `json:"garrison_percent"`
	TaxRatePercent     int32   `json:"tax_rate_percent"`
	StartX             int32   `json:"start_x"`
	StartY             int32   `json:"start_y"`
	Size               int32   `json:"size"`
	CityID             string  `json:"city_id"`
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) error {
	_, err := q.db.Exec(ctx, updateCity,
		arg.Type,
		arg.Owner,
		arg.Name,
		arg.Population,
		arg.PopulationCap,
		arg.GarrisonPopulation,
		arg.GarrisonPercent,
		arg.TaxRatePercent,
		arg.StartX,
		arg.StartY,
		arg.Size,
		arg.CityID,
	)
	return err
}
