// Package database providers an implementation of the database Querier interface generated by sqlc.
package database

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5/pgxpool"
	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"

	"cityio/internal/ports"
)

func NewDB(log ports.Logger) Querier {
	var dsn string
	if os.Getenv("ENVIRONMENT") == "production" {
		log.Info("Using production database")
		dsn = fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=5432",
			os.Getenv("PSQL_HOST_PROD"),
			os.Getenv("PSQL_USERNAME_PROD"),
			os.Getenv("PSQL_PASSWORD_PROD"),
			os.Getenv("PSQL_DATABASE_PROD"))
	} else {
		log.Info("Using development database")
		dsn = fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=5432",
			os.Getenv("PSQL_HOST_DEV"),
			os.Getenv("PSQL_USERNAME_DEV"),
			os.Getenv("PSQL_PASSWORD_DEV"),
			os.Getenv("PSQL_DATABASE_DEV"))
	}

	pool, err := pgxpool.New(context.Background(), dsn)
	if err != nil {
		log.Error("failed to create pgx pool", "error", err)
		os.Exit(1)
	}

	migrations, err := goose.OpenDBWithDriver("pgx", dsn)
	if err != nil {
		log.Error("failed to open goose DB connection", "error", err)
		os.Exit(1)
	}

	if err := goose.RunContext(
		context.Background(),
		"down-to",
		migrations,
		"db/migrations",
		"0",
	); err != nil {
		log.Error("failed to open goose reset migration", "error", err)
		os.Exit(1)
	}

	if err := goose.RunContext(
		context.Background(),
		"up",
		migrations,
		"db/migrations",
	); err != nil {
		log.Error("failed to open goose apply migration", "error", err)
		os.Exit(1)
	}

	return New(pool)
}
