// Package database providers an implementation of the database Querier interface generated by sqlc.
package database

import (
	"context"
	"database/sql"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5"
	"github.com/pressly/goose/v3"

	"cityio/internal/ports"
)

func NewDB(log ports.Logger) (Querier, *sql.DB) {
	var dsn string
	if os.Getenv("ENVIRONMENT") == "production" {
		log.Info("Using production database")
		dsn = fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=5432",
			os.Getenv("PSQL_HOST_PROD"),
			os.Getenv("PSQL_USERNAME_PROD"),
			os.Getenv("PSQL_PASSWORD_PROD"),
			os.Getenv("PSQL_DATABASE_PROD"))
	} else {
		log.Info("Using development database")
		dsn = fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=5432",
			os.Getenv("PSQL_HOST_DEV"),
			os.Getenv("PSQL_USERNAME_DEV"),
			os.Getenv("PSQL_PASSWORD_DEV"),
			os.Getenv("PSQL_DATABASE_DEV"))
	}

	var err error
	db, err := pgx.Connect(context.Background(), dsn)
	if err != nil {
		log.Error("failed to open DB connection", "error", err)
		os.Exit(1)
	}

	migrations, err := goose.OpenDBWithDriver("postgresql", dsn)
	if err != nil {
		log.Error("failed to open goose DB connection", "error", err)
	}

	return New(db), migrations
}
