// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: explored_tiles.sql

package database

import (
	"context"
)

const addExploredTiles = `-- name: AddExploredTiles :exec
INSERT INTO explored_tiles (user_id, tile_x, tile_y)
SELECT $1, discovered.x, discovered.y
FROM (
    SELECT
        UNNEST($2::int[]) AS x,
        UNNEST($3::int[]) AS y
) AS discovered
ON CONFLICT (user_id, tile_x, tile_y) DO NOTHING
`

type AddExploredTilesParams struct {
	UserID string  `json:"user_id"`
	TileXs []int32 `json:"tile_xs"`
	TileYs []int32 `json:"tile_ys"`
}

func (q *Queries) AddExploredTiles(ctx context.Context, arg AddExploredTilesParams) error {
	_, err := q.db.Exec(ctx, addExploredTiles, arg.UserID, arg.TileXs, arg.TileYs)
	return err
}

const getExploredTiles = `-- name: GetExploredTiles :many
SELECT tile_x, tile_y
FROM explored_tiles
WHERE user_id = $1
ORDER BY tile_y, tile_x
`

type GetExploredTilesRow struct {
	TileX int32 `json:"tile_x"`
	TileY int32 `json:"tile_y"`
}

func (q *Queries) GetExploredTiles(ctx context.Context, userID string) ([]GetExploredTilesRow, error) {
	rows, err := q.db.Query(ctx, getExploredTiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExploredTilesRow
	for rows.Next() {
		var i GetExploredTilesRow
		if err := rows.Scan(&i.TileX, &i.TileY); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
