// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailbox_messages.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMailboxMessage = `-- name: CreateMailboxMessage :exec
INSERT INTO mailbox_messages (
    mailbox_message_id,
    recipient_id,
    kind,
    payload,
    created_at,
    read_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateMailboxMessageParams struct {
	MailboxMessageID string           `json:"mailbox_message_id"`
	RecipientID      string           `json:"recipient_id"`
	Kind             string           `json:"kind"`
	Payload          []byte           `json:"payload"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	ReadAt           pgtype.Timestamp `json:"read_at"`
}

func (q *Queries) CreateMailboxMessage(ctx context.Context, arg CreateMailboxMessageParams) error {
	_, err := q.db.Exec(ctx, createMailboxMessage,
		arg.MailboxMessageID,
		arg.RecipientID,
		arg.Kind,
		arg.Payload,
		arg.CreatedAt,
		arg.ReadAt,
	)
	return err
}

const getMailboxMessagesByRecipient = `-- name: GetMailboxMessagesByRecipient :many
SELECT mailbox_message_id, recipient_id, kind, payload, created_at, read_at
FROM mailbox_messages
WHERE recipient_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) GetMailboxMessagesByRecipient(ctx context.Context, recipientID string) ([]MailboxMessage, error) {
	rows, err := q.db.Query(ctx, getMailboxMessagesByRecipient, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailboxMessage
	for rows.Next() {
		var i MailboxMessage
		if err := rows.Scan(
			&i.MailboxMessageID,
			&i.RecipientID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMailboxMessageRead = `-- name: MarkMailboxMessageRead :one
UPDATE mailbox_messages
SET read_at = COALESCE(read_at, NOW())
WHERE mailbox_message_id = $1
  AND recipient_id = $2
RETURNING mailbox_message_id, recipient_id, kind, payload, created_at, read_at
`

type MarkMailboxMessageReadParams struct {
	MailboxMessageID string `json:"mailbox_message_id"`
	RecipientID      string `json:"recipient_id"`
}

func (q *Queries) MarkMailboxMessageRead(ctx context.Context, arg MarkMailboxMessageReadParams) (MailboxMessage, error) {
	row := q.db.QueryRow(ctx, markMailboxMessageRead, arg.MailboxMessageID, arg.RecipientID)
	var i MailboxMessage
	err := row.Scan(
		&i.MailboxMessageID,
		&i.RecipientID,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}
