// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"cityio/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type Army struct {
	ArmyID       string             `json:"army_id"`
	Owner        string             `json:"owner"`
	Coords       domain.Coordinates `json:"coords"`
	Troops       []byte             `json:"troops"`
	DestX        *int32             `json:"dest_x"`
	DestY        *int32             `json:"dest_y"`
	UpkeepCityID *string            `json:"upkeep_city_id"`
	CreatedAt    pgtype.Timestamp   `json:"created_at"`
	UpdatedAt    pgtype.Timestamp   `json:"updated_at"`
}

type Building struct {
	BuildingID        string             `json:"building_id"`
	CityID            string             `json:"city_id"`
	Type              string             `json:"type"`
	Level             int32              `json:"level"`
	Coords            domain.Coordinates `json:"coords"`
	ConstructionStart pgtype.Timestamp   `json:"construction_start"`
	ConstructionEnd   pgtype.Timestamp   `json:"construction_end"`
	CreatedAt         pgtype.Timestamp   `json:"created_at"`
	UpdatedAt         pgtype.Timestamp   `json:"updated_at"`
}

type City struct {
	CityID        string             `json:"city_id"`
	Type          string             `json:"type"`
	Owner         *string            `json:"owner"`
	Name          string             `json:"name"`
	Population    float64            `json:"population"`
	PopulationCap float64            `json:"population_cap"`
	StartCoords   domain.Coordinates `json:"start_coords"`
	Size          int32              `json:"size"`
	CreatedAt     pgtype.Timestamp   `json:"created_at"`
	UpdatedAt     pgtype.Timestamp   `json:"updated_at"`
}

type TrainingOrder struct {
	TrainingOrderID string           `json:"training_order_id"`
	ArmyID          string           `json:"army_id"`
	BarracksID      string           `json:"barracks_id"`
	TroopType       string           `json:"troop_type"`
	Count           int64            `json:"count"`
	PopulationCost  int64            `json:"population_cost"`
	GoldCost        int64            `json:"gold_cost"`
	StartedAt       pgtype.Timestamp `json:"started_at"`
	CompletesAt     pgtype.Timestamp `json:"completes_at"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type User struct {
	UserID    string           `json:"user_id"`
	Email     string           `json:"email"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	Gold      int64            `json:"gold"`
	Food      int64            `json:"food"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
