// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"cityio/internal/models"
	"github.com/jackc/pgx/v5/pgtype"
)

type City struct {
	CityID        string             `json:"city_id"`
	Type          string             `json:"type"`
	Owner         *string            `json:"owner"`
	Name          string             `json:"name"`
	Population    float64            `json:"population"`
	PopulationCap float64            `json:"population_cap"`
	StartCoords   models.Coordinates `json:"start_coords"`
	Size          int32              `json:"size"`
	CreatedAt     pgtype.Timestamp   `json:"created_at"`
	UpdatedAt     pgtype.Timestamp   `json:"updated_at"`
}

type MapTile struct {
	Coords     models.Coordinates `json:"coords"`
	CityID     *string            `json:"city_id"`
	BuildingID *string            `json:"building_id"`
}

type User struct {
	UserID    string           `json:"user_id"`
	Email     string           `json:"email"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	Gold      int64            `json:"gold"`
	Food      int64            `json:"food"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
