// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	BatchCreateArmies(ctx context.Context, arg BatchCreateArmiesParams) error
	BatchCreateBuildings(ctx context.Context, arg BatchCreateBuildingsParams) error
	BatchCreateCities(ctx context.Context, arg BatchCreateCitiesParams) error
	BatchUpdateArmies(ctx context.Context, arg BatchUpdateArmiesParams) error
	BatchUpdateBuildings(ctx context.Context, arg BatchUpdateBuildingsParams) error
	BatchUpdateCities(ctx context.Context, arg BatchUpdateCitiesParams) error
	BatchUpdateUsers(ctx context.Context, arg BatchUpdateUsersParams) error
	CreateArmy(ctx context.Context, arg CreateArmyParams) error
	CreateBuilding(ctx context.Context, arg CreateBuildingParams) error
	CreateCity(ctx context.Context, arg CreateCityParams) error
	CreateTrainingOrder(ctx context.Context, arg CreateTrainingOrderParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteArmy(ctx context.Context, armyID string) error
	DeleteBuilding(ctx context.Context, buildingID string) error
	DeleteCity(ctx context.Context, cityID string) error
	DeleteTrainingOrder(ctx context.Context, trainingOrderID string) error
	DeleteUser(ctx context.Context, userID string) error
	GetAllArmies(ctx context.Context) ([]GetAllArmiesRow, error)
	GetAllBuildings(ctx context.Context) ([]GetAllBuildingsRow, error)
	GetAllCities(ctx context.Context) ([]GetAllCitiesRow, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetBuildingsByCity(ctx context.Context, cityID string) ([]GetBuildingsByCityRow, error)
	GetCitiesByOwner(ctx context.Context, owner *string) ([]GetCitiesByOwnerRow, error)
	GetTrainingOrdersByBarracks(ctx context.Context, barracksID string) ([]TrainingOrder, error)
	GetUserByIdentifier(ctx context.Context, email string) (User, error)
	StartTrainingOrder(ctx context.Context, arg StartTrainingOrderParams) error
	UpdateCity(ctx context.Context, arg UpdateCityParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) error
}

var _ Querier = (*Queries)(nil)
