// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	BatchUpdateCities(ctx context.Context, arg BatchUpdateCitiesParams) error
	BatchUpdateUsers(ctx context.Context, arg BatchUpdateUsersParams) error
	CreateCity(ctx context.Context, arg CreateCityParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteCity(ctx context.Context, cityID string) error
	DeleteUser(ctx context.Context, userID string) error
	GetAllCities(ctx context.Context) ([]City, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	UpdateCity(ctx context.Context, arg UpdateCityParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) error
}

var _ Querier = (*Queries)(nil)
