// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tiles.sql

package database

import (
	"context"
)

const getAllTiles = `-- name: GetAllTiles :many
SELECT coords, city_id, building_id FROM tiles
`

func (q *Queries) GetAllTiles(ctx context.Context) ([]Tile, error) {
	rows, err := q.db.Query(ctx, getAllTiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tile
	for rows.Next() {
		var i Tile
		if err := rows.Scan(&i.Coords, &i.CityID, &i.BuildingID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
