// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training_orders.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrainingOrder = `-- name: CreateTrainingOrder :exec
INSERT INTO training_orders (
    training_order_id,
    army_id,
    barracks_id,
    troop_type,
    count,
    population_cost,
    gold_cost,
    started_at,
    completes_at,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateTrainingOrderParams struct {
	TrainingOrderID string           `json:"training_order_id"`
	ArmyID          string           `json:"army_id"`
	BarracksID      string           `json:"barracks_id"`
	TroopType       string           `json:"troop_type"`
	Count           int64            `json:"count"`
	PopulationCost  int64            `json:"population_cost"`
	GoldCost        int64            `json:"gold_cost"`
	StartedAt       pgtype.Timestamp `json:"started_at"`
	CompletesAt     pgtype.Timestamp `json:"completes_at"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateTrainingOrder(ctx context.Context, arg CreateTrainingOrderParams) error {
	_, err := q.db.Exec(ctx, createTrainingOrder,
		arg.TrainingOrderID,
		arg.ArmyID,
		arg.BarracksID,
		arg.TroopType,
		arg.Count,
		arg.PopulationCost,
		arg.GoldCost,
		arg.StartedAt,
		arg.CompletesAt,
		arg.CreatedAt,
	)
	return err
}

const deleteTrainingOrder = `-- name: DeleteTrainingOrder :exec
DELETE FROM training_orders
WHERE training_order_id = $1
`

func (q *Queries) DeleteTrainingOrder(ctx context.Context, trainingOrderID string) error {
	_, err := q.db.Exec(ctx, deleteTrainingOrder, trainingOrderID)
	return err
}

const getTrainingOrdersByBarracks = `-- name: GetTrainingOrdersByBarracks :many
SELECT training_order_id, army_id, barracks_id, troop_type, count, population_cost, gold_cost, started_at, completes_at, created_at
FROM training_orders
WHERE barracks_id = $1
ORDER BY created_at, training_order_id
`

func (q *Queries) GetTrainingOrdersByBarracks(ctx context.Context, barracksID string) ([]TrainingOrder, error) {
	rows, err := q.db.Query(ctx, getTrainingOrdersByBarracks, barracksID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingOrder
	for rows.Next() {
		var i TrainingOrder
		if err := rows.Scan(
			&i.TrainingOrderID,
			&i.ArmyID,
			&i.BarracksID,
			&i.TroopType,
			&i.Count,
			&i.PopulationCost,
			&i.GoldCost,
			&i.StartedAt,
			&i.CompletesAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTrainingOrder = `-- name: StartTrainingOrder :exec
UPDATE training_orders
SET
    started_at = $2,
    completes_at = $3
WHERE training_order_id = $1
`

type StartTrainingOrderParams struct {
	TrainingOrderID string           `json:"training_order_id"`
	StartedAt       pgtype.Timestamp `json:"started_at"`
	CompletesAt     pgtype.Timestamp `json:"completes_at"`
}

func (q *Queries) StartTrainingOrder(ctx context.Context, arg StartTrainingOrderParams) error {
	_, err := q.db.Exec(ctx, startTrainingOrder, arg.TrainingOrderID, arg.StartedAt, arg.CompletesAt)
	return err
}
