// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const batchUpdateUsers = `-- name: BatchUpdateUsers :exec
UPDATE users AS u
SET
    gold        = v.gold,
    food        = v.food,
    updated_at  = NOW()
FROM (
    SELECT
        UNNEST($1::text[])  AS user_id,
        UNNEST($2::int8[])     AS gold,
        UNNEST($3::int8[])     AS food
) AS v
WHERE u.user_id = v.user_id
`

type BatchUpdateUsersParams struct {
	UserIds []string `json:"user_ids"`
	Golds   []int64  `json:"golds"`
	Foods   []int64  `json:"foods"`
}

func (q *Queries) BatchUpdateUsers(ctx context.Context, arg BatchUpdateUsersParams) error {
	_, err := q.db.Exec(ctx, batchUpdateUsers, arg.UserIds, arg.Golds, arg.Foods)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    user_id, email, username, password, gold, food, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
`

type CreateUserParams struct {
	UserID   string `json:"user_id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Gold     int64  `json:"gold"`
	Food     int64  `json:"food"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Gold,
		arg.Food,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT user_id, email, username, password, gold, food, created_at, updated_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.Gold,
			&i.Food,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    username   = $2,
    gold       = $3,
    food       = $4,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	Gold     int64  `json:"gold"`
	Food     int64  `json:"food"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.UserID,
		arg.Username,
		arg.Gold,
		arg.Food,
	)
	return err
}

const updateUserStats = `-- name: UpdateUserStats :exec
UPDATE users
SET
    gold       = $2,
    food       = $3,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserStatsParams struct {
	UserID string `json:"user_id"`
	Gold   int64  `json:"gold"`
	Food   int64  `json:"food"`
}

func (q *Queries) UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) error {
	_, err := q.db.Exec(ctx, updateUserStats, arg.UserID, arg.Gold, arg.Food)
	return err
}
