// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const batchUpdateUsers = `-- name: BatchUpdateUsers :exec
UPDATE users AS u
SET
    email      = v.email,
    username   = v.username,
    password   = v.password,
    gold       = v.gold,
    food       = v.food,
    updated_at = NOW()
FROM (
    SELECT
        unnest($1::text[])     AS user_id,
        unnest($2::text[])     AS email,
        unnest($3::text[])     AS username,
        unnest($4::text[])     AS password,
        unnest($5::bigint[])   AS gold,
        unnest($6::bigint[])   AS food
) AS v
WHERE u.user_id = v.user_id
`

type BatchUpdateUsersParams struct {
	Column1 []string `json:"column_1"`
	Column2 []string `json:"column_2"`
	Column3 []string `json:"column_3"`
	Column4 []string `json:"column_4"`
	Column5 []int64  `json:"column_5"`
	Column6 []int64  `json:"column_6"`
}

func (q *Queries) BatchUpdateUsers(ctx context.Context, arg BatchUpdateUsersParams) error {
	_, err := q.db.Exec(ctx, batchUpdateUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    user_id, email, username, password, gold, food
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateUserParams struct {
	UserID   string `json:"user_id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Gold     int64  `json:"gold"`
	Food     int64  `json:"food"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Gold,
		arg.Food,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    email      = $2,
    username   = $3,
    password   = $4,
    gold       = $5,
    food       = $6,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID   string `json:"user_id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Gold     int64  `json:"gold"`
	Food     int64  `json:"food"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.UserID,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Gold,
		arg.Food,
	)
	return err
}
