// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const batchUpdateUsers = `-- name: BatchUpdateUsers :exec
UPDATE users AS u
SET
    gold             = v.gold,
    food             = v.food,
    food_income_rate = v.food_income_rate,
    food_upkeep_rate = v.food_upkeep_rate,
    updated_at       = NOW()
FROM (
    SELECT
        UNNEST($1::text[])             AS user_id,
        UNNEST($2::int8[])                AS gold,
        UNNEST($3::int8[])                AS food,
        UNNEST($4::float8[])  AS food_income_rate,
        UNNEST($5::float8[])  AS food_upkeep_rate
) AS v
WHERE u.user_id = v.user_id
`

type BatchUpdateUsersParams struct {
	UserIds         []string  `json:"user_ids"`
	Golds           []int64   `json:"golds"`
	Foods           []int64   `json:"foods"`
	FoodIncomeRates []float64 `json:"food_income_rates"`
	FoodUpkeepRates []float64 `json:"food_upkeep_rates"`
}

func (q *Queries) BatchUpdateUsers(ctx context.Context, arg BatchUpdateUsersParams) error {
	_, err := q.db.Exec(ctx, batchUpdateUsers,
		arg.UserIds,
		arg.Golds,
		arg.Foods,
		arg.FoodIncomeRates,
		arg.FoodUpkeepRates,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    user_id, email, username, password, gold, food
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateUserParams struct {
	UserID   string `json:"user_id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Gold     int64  `json:"gold"`
	Food     int64  `json:"food"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Gold,
		arg.Food,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT user_id, email, username, password, gold, food, created_at, updated_at, food_income_rate, food_upkeep_rate FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.Gold,
			&i.Food,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FoodIncomeRate,
			&i.FoodUpkeepRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByIdentifier = `-- name: GetUserByIdentifier :one
SELECT user_id, email, username, password, gold, food, created_at, updated_at, food_income_rate, food_upkeep_rate FROM users
WHERE email = $1 OR username = $1
`

func (q *Queries) GetUserByIdentifier(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentifier, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Gold,
		&i.Food,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FoodIncomeRate,
		&i.FoodUpkeepRate,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    username   = $2,
    gold       = $3,
    food       = $4,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	Gold     int64  `json:"gold"`
	Food     int64  `json:"food"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.UserID,
		arg.Username,
		arg.Gold,
		arg.Food,
	)
	return err
}

const updateUserStats = `-- name: UpdateUserStats :exec
UPDATE users
SET
    gold       = $2,
    food       = $3,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserStatsParams struct {
	UserID string `json:"user_id"`
	Gold   int64  `json:"gold"`
	Food   int64  `json:"food"`
}

func (q *Queries) UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) error {
	_, err := q.db.Exec(ctx, updateUserStats, arg.UserID, arg.Gold, arg.Food)
	return err
}
