// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: world_state.sql

package database

import (
	"context"
)

const getOrCreateWorldSeed = `-- name: GetOrCreateWorldSeed :one
INSERT INTO world_state (id, seed)
VALUES (1, $1)
ON CONFLICT (id) DO UPDATE
SET seed = world_state.seed
RETURNING seed
`

func (q *Queries) GetOrCreateWorldSeed(ctx context.Context, seed int64) (int64, error) {
	row := q.db.QueryRow(ctx, getOrCreateWorldSeed, seed)
	var seed_2 int64
	err := row.Scan(&seed_2)
	return seed_2, err
}
