package constants

const (
	MAP_SIZE  = 1024
	CITY_SIZE = 5

	POPULATION_GROWTH_RATE  = 0.005
	INITIAL_TOWN_POPULATION = 100

	INITIAL_PLAYER_CITY_POPULATION = 250
	INITIAL_PLAYER_GOLD            = 100000
	INITIAL_PLAYER_FOOD            = 100000

	// in seconds
	DB_BACKUP_FREQUENCY           = 3
	USER_BACKUP_FREQUENCY         = 10
	CITY_BACKUP_FREQUENCY         = 10
	BUILDING_PRODUCTION_FREQUENCY = 3
)
